"""empty message

Revision ID: 7436e47fd62d
Revises: 
Create Date: 2022-03-20 02:17:49.530492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7436e47fd62d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('numofbedrooms', sa.String(), nullable=True),
    sa.Column('numofbathrooms', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('ptype', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_profile')
    # ### end Alembic commands ###
